/**
 * Catálogo de veículos elétricos — EV Brasil
 * -------------------------------------------------
 * Este é o "banco de dados" do site. Para adicionar, remover ou editar
 * um carro, basta alterar os objetos abaixo. Cada campo é usado
 * automaticamente nas páginas de listagem e de detalhes.
 *
 * Dica: mantenha o campo `id` único (usado na URL: veiculo.html?id=...).
 */

const VEHICLES = [
  {
    id: "byd-dolphin",
    brand: "BYD",
    model: "Dolphin",
    tagline: "O elétrico urbano perfeito para o dia a dia.",
    priceBRL: 149800,
    bodyType: "Hatch",
    segment: "Compacto",
    color: "#3b82f6",
    year: 2025,
    featured: true,
    specs: {
      autonomia: "291 km (WLTP)",
      bateria: "44,9 kWh (Blade)",
      potencia: "95 cv",
      torque: "180 Nm",
      aceleracao: "0–100 km/h em 12,3 s",
      velocidadeMax: "150 km/h",
      tracao: "Dianteira",
      recargaAC: "7 kW — 100% em ~6h30",
      recargaDC: "60 kW — 30% a 80% em ~30 min",
      lugares: 5,
      portaMalas: "345 L",
    },
    highlights: [
      "Bateria Blade LFP, referência em segurança",
      "Central multimídia rotativa de 12,8\"",
      "Pacote completo de assistências (ADAS)",
    ],
    description:
      "O BYD Dolphin combina eficiência, tecnologia e um preço competitivo. Ideal para quem quer entrar no mundo elétrico sem abrir mão de conforto e conectividade nas cidades brasileiras.",
  },
  {
    id: "byd-dolphin-mini",
    brand: "BYD",
    model: "Dolphin Mini",
    tagline: "O elétrico mais acessível do Brasil.",
    priceBRL: 115800,
    bodyType: "Hatch",
    segment: "Entrada",
    color: "#22d3ee",
    year: 2025,
    featured: true,
    specs: {
      autonomia: "280 km (NEDC)",
      bateria: "38 kWh (Blade)",
      potencia: "75 cv",
      torque: "135 Nm",
      aceleracao: "0–100 km/h em 14,9 s",
      velocidadeMax: "130 km/h",
      tracao: "Dianteira",
      recargaAC: "6,6 kW — 100% em ~6h",
      recargaDC: "40 kW — 30% a 80% em ~30 min",
      lugares: 5,
      portaMalas: "230 L",
    },
    highlights: [
      "Porta de entrada para a mobilidade elétrica",
      "Compacto por fora, espaçoso por dentro",
      "Baixíssimo custo por quilômetro rodado",
    ],
    description:
      "O Dolphin Mini é a escolha inteligente para o primeiro carro elétrico. Econômico, ágil no trânsito e com a confiabilidade da bateria Blade da BYD.",
  },
  {
    id: "byd-seal",
    brand: "BYD",
    model: "Seal",
    tagline: "Desempenho esportivo, elegância elétrica.",
    priceBRL: 296800,
    bodyType: "Sedã",
    segment: "Premium",
    color: "#6366f1",
    year: 2025,
    featured: true,
    specs: {
      autonomia: "570 km (CLTC)",
      bateria: "82,5 kWh (Blade)",
      potencia: "530 cv (AWD)",
      torque: "670 Nm",
      aceleracao: "0–100 km/h em 3,8 s",
      velocidadeMax: "180 km/h",
      tracao: "Integral (AWD)",
      recargaAC: "11 kW — 100% em ~8h",
      recargaDC: "150 kW — 30% a 80% em ~26 min",
      lugares: 5,
      portaMalas: "400 L",
    },
    highlights: [
      "Plataforma e-Platform 3.0 com bateria estrutural",
      "Aceleração de superesportivo",
      "Design aerodinâmico inspirado no oceano",
    ],
    description:
      "O BYD Seal é um sedã esportivo que entrega desempenho de tirar o fôlego com sofisticação. Um rival direto dos elétricos premium mundiais, agora no Brasil.",
  },
  {
    id: "byd-yuan-plus",
    brand: "BYD",
    model: "Yuan Plus",
    tagline: "O SUV elétrico para toda a família.",
    priceBRL: 237800,
    bodyType: "SUV",
    segment: "Familiar",
    color: "#0ea5e9",
    year: 2025,
    featured: false,
    specs: {
      autonomia: "430 km (NEDC)",
      bateria: "60,5 kWh (Blade)",
      potencia: "204 cv",
      torque: "310 Nm",
      aceleracao: "0–100 km/h em 7,3 s",
      velocidadeMax: "160 km/h",
      tracao: "Dianteira",
      recargaAC: "7 kW — 100% em ~9h",
      recargaDC: "80 kW — 30% a 80% em ~30 min",
      lugares: 5,
      portaMalas: "440 L",
    },
    highlights: [
      "Espaço interno generoso e versátil",
      "Interior com acabamento premium",
      "Ótimo equilíbrio entre autonomia e preço",
    ],
    description:
      "O Yuan Plus é o SUV elétrico completo: espaçoso, confortável e tecnológico. Perfeito para famílias que buscam segurança e economia no dia a dia e nas viagens.",
  },
  {
    id: "byd-han",
    brand: "BYD",
    model: "Han",
    tagline: "Luxo e autonomia sem compromissos.",
    priceBRL: 389800,
    bodyType: "Sedã",
    segment: "Luxo",
    color: "#8b5cf6",
    year: 2025,
    featured: false,
    specs: {
      autonomia: "605 km (NEDC)",
      bateria: "85,4 kWh (Blade)",
      potencia: "517 cv (AWD)",
      torque: "700 Nm",
      aceleracao: "0–100 km/h em 3,9 s",
      velocidadeMax: "180 km/h",
      tracao: "Integral (AWD)",
      recargaAC: "11 kW — 100% em ~8h",
      recargaDC: "170 kW — 30% a 80% em ~25 min",
      lugares: 5,
      portaMalas: "410 L",
    },
    highlights: [
      "Interior de luxo com acabamento em couro Nappa",
      "Sistema de som premium",
      "A joia da coroa da linha BYD",
    ],
    description:
      "O BYD Han é a expressão máxima de luxo elétrico da marca. Combina autonomia de longa distância, desempenho impressionante e um interior digno das melhores limusines.",
  },
  {
    id: "byd-song-plus",
    brand: "BYD",
    model: "Song Plus DM-i",
    tagline: "SUV híbrido plug-in de alta autonomia.",
    priceBRL: 259800,
    bodyType: "SUV",
    segment: "Familiar",
    color: "#14b8a6",
    year: 2025,
    featured: false,
    specs: {
      autonomia: "1.100 km (combinada)",
      bateria: "18,3 kWh + motor 1.5",
      potencia: "235 cv (combinada)",
      torque: "325 Nm",
      aceleracao: "0–100 km/h em 8,5 s",
      velocidadeMax: "170 km/h",
      tracao: "Dianteira",
      recargaAC: "6,6 kW — 100% em ~3h",
      recargaDC: "não aplicável",
      lugares: 5,
      portaMalas: "574 L",
    },
    highlights: [
      "Tecnologia híbrida plug-in DM-i",
      "Autonomia combinada para longas viagens",
      "Sem ansiedade de recarga",
    ],
    description:
      "O Song Plus DM-i une o melhor dos dois mundos: dirija no modo elétrico na cidade e conte com o motor a combustão para viagens longas, com autonomia combinada superior a 1.000 km.",
  },
  {
    id: "gwm-ora-03",
    brand: "GWM",
    model: "Ora 03",
    tagline: "Estilo retrô, alma elétrica.",
    priceBRL: 179900,
    bodyType: "Hatch",
    segment: "Compacto",
    color: "#f59e0b",
    year: 2025,
    featured: false,
    specs: {
      autonomia: "310 km (WLTP)",
      bateria: "48 kWh",
      potencia: "171 cv",
      torque: "250 Nm",
      aceleracao: "0–100 km/h em 8,4 s",
      velocidadeMax: "160 km/h",
      tracao: "Dianteira",
      recargaAC: "11 kW — 100% em ~6h",
      recargaDC: "64 kW — 30% a 80% em ~40 min",
      lugares: 5,
      portaMalas: "228 L",
    },
    highlights: [
      "Design icônico e cativante",
      "Interior tecnológico com telas duplas",
      "Ótimo pacote de série",
    ],
    description:
      "O GWM Ora 03 chama a atenção pelo visual retrô-futurista e entrega uma experiência elétrica divertida, bem equipada e cheia de personalidade.",
  },
  {
    id: "byd-tan",
    brand: "BYD",
    model: "Tan",
    tagline: "SUV de 7 lugares, potência e espaço.",
    priceBRL: 519800,
    bodyType: "SUV",
    segment: "Luxo",
    color: "#ef4444",
    year: 2025,
    featured: false,
    specs: {
      autonomia: "400 km (NEDC)",
      bateria: "108,8 kWh (Blade)",
      potencia: "517 cv (AWD)",
      torque: "680 Nm",
      aceleracao: "0–100 km/h em 4,6 s",
      velocidadeMax: "180 km/h",
      tracao: "Integral (AWD)",
      recargaAC: "11 kW — 100% em ~10h",
      recargaDC: "170 kW — 30% a 80% em ~30 min",
      lugares: 7,
      portaMalas: "235 L (7 lug.) / 940 L (5 lug.)",
    },
    highlights: [
      "Sete lugares reais e confortáveis",
      "Desempenho de esportivo em um SUV grande",
      "Tecnologia de ponta em toda a cabine",
    ],
    description:
      "O BYD Tan é o SUV elétrico de sete lugares para quem não abre mão de espaço, potência e sofisticação. Ideal para famílias grandes e para quem viaja em grupo.",
  },

  /* ---------- Outras marcas ---------- */
  {
    id: "volvo-ex30",
    brand: "Volvo",
    model: "EX30",
    tagline: "O Volvo mais compacto e mais rápido.",
    priceBRL: 229950,
    bodyType: "SUV",
    segment: "Premium",
    color: "#38bdf8",
    year: 2025,
    featured: true,
    specs: {
      autonomia: "338 km (Inmetro)",
      bateria: "69 kWh",
      potencia: "272 cv",
      torque: "343 Nm",
      aceleracao: "0–100 km/h em 5,3 s",
      velocidadeMax: "180 km/h",
      tracao: "Traseira",
      recargaAC: "11 kW — 100% em ~8h",
      recargaDC: "153 kW — 10% a 80% em ~28 min",
      lugares: 5,
      portaMalas: "318 L",
    },
    highlights: [
      "Design escandinavo minimalista",
      "Pacote de segurança referência da marca",
      "Central vertical de 12,3\" com Google integrado",
    ],
    description:
      "O Volvo EX30 leva o DNA de segurança e o design escandinavo para um SUV compacto e ágil. É a porta de entrada da marca no mundo elétrico, com desempenho de carro esportivo.",
  },
  {
    id: "renault-kwid-e-tech",
    brand: "Renault",
    model: "Kwid E-Tech",
    tagline: "Elétrico de entrada para a cidade.",
    priceBRL: 99990,
    bodyType: "Hatch",
    segment: "Entrada",
    color: "#34d399",
    year: 2025,
    featured: false,
    specs: {
      autonomia: "185 km (Inmetro)",
      bateria: "26,8 kWh",
      potencia: "65 cv",
      torque: "113 Nm",
      aceleracao: "0–100 km/h em 14,6 s",
      velocidadeMax: "130 km/h",
      tracao: "Dianteira",
      recargaAC: "7 kW — 100% em ~4h",
      recargaDC: "30 kW — 15% a 80% em ~40 min",
      lugares: 4,
      portaMalas: "290 L",
    },
    highlights: [
      "Um dos elétricos mais baratos do país",
      "Compacto e fácil de estacionar",
      "Custo por km muito baixo",
    ],
    description:
      "O Renault Kwid E-Tech é a forma mais simples de trocar o posto pela tomada. Pequeno por fora e esperto no trânsito, foi feito para o uso urbano do dia a dia.",
  },
  {
    id: "fiat-500e",
    brand: "Fiat",
    model: "500e",
    tagline: "Ícone italiano, agora elétrico.",
    priceBRL: 214990,
    bodyType: "Hatch",
    segment: "Urbano",
    color: "#2dd4bf",
    year: 2025,
    featured: false,
    specs: {
      autonomia: "320 km (WLTP)",
      bateria: "42 kWh",
      potencia: "118 cv",
      torque: "220 Nm",
      aceleracao: "0–100 km/h em 9,0 s",
      velocidadeMax: "150 km/h",
      tracao: "Dianteira",
      recargaAC: "11 kW — 100% em ~4h15",
      recargaDC: "85 kW — 0% a 80% em ~35 min",
      lugares: 4,
      portaMalas: "185 L",
    },
    highlights: [
      "Design clássico reinterpretado",
      "Recarga rápida de 85 kW",
      "Acabamento caprichado para o tamanho",
    ],
    description:
      "O Fiat 500e mantém o charme do Cinquecento e troca o motor a combustão por um conjunto elétrico silencioso e ágil. Um carro de cidade com muita personalidade.",
  },
  {
    id: "peugeot-e-2008",
    brand: "Peugeot",
    model: "e-2008",
    tagline: "SUV compacto com assinatura francesa.",
    priceBRL: 259990,
    bodyType: "SUV",
    segment: "Compacto",
    color: "#60a5fa",
    year: 2025,
    featured: false,
    specs: {
      autonomia: "345 km (WLTP)",
      bateria: "50 kWh",
      potencia: "136 cv",
      torque: "260 Nm",
      aceleracao: "0–100 km/h em 9,9 s",
      velocidadeMax: "150 km/h",
      tracao: "Dianteira",
      recargaAC: "7,4 kW — 100% em ~7h30",
      recargaDC: "100 kW — 0% a 80% em ~30 min",
      lugares: 5,
      portaMalas: "434 L",
    },
    highlights: [
      "Painel i-Cockpit 3D",
      "Porta-malas generoso para a categoria",
      "Rodar confortável e silencioso",
    ],
    description:
      "O Peugeot e-2008 combina o visual marcante da marca com a praticidade de um SUV compacto. Cabine tecnológica e bom espaço para a família no uso diário.",
  },
  {
    id: "nissan-leaf",
    brand: "Nissan",
    model: "Leaf",
    tagline: "O pioneiro dos elétricos.",
    priceBRL: 298490,
    bodyType: "Hatch",
    segment: "Médio",
    color: "#818cf8",
    year: 2024,
    featured: false,
    specs: {
      autonomia: "272 km (WLTP)",
      bateria: "40 kWh",
      potencia: "149 cv",
      torque: "320 Nm",
      aceleracao: "0–100 km/h em 7,9 s",
      velocidadeMax: "144 km/h",
      tracao: "Dianteira",
      recargaAC: "6,6 kW — 100% em ~7h",
      recargaDC: "50 kW — 20% a 80% em ~40 min",
      lugares: 5,
      portaMalas: "435 L",
    },
    highlights: [
      "Mais de uma década de histórico elétrico",
      "e-Pedal: dirija usando só o acelerador",
      "Porta-malas de carro médio",
    ],
    description:
      "O Nissan Leaf é um dos elétricos mais vendidos da história. Confiável e confortável, é uma escolha madura para quem quer um hatch médio sem surpresas.",
  },
  {
    id: "bmw-ix1",
    brand: "BMW",
    model: "iX1",
    tagline: "O SUV de entrada da BMW, elétrico.",
    priceBRL: 359950,
    bodyType: "SUV",
    segment: "Premium",
    color: "#3b82f6",
    year: 2025,
    featured: false,
    specs: {
      autonomia: "475 km (WLTP)",
      bateria: "64,7 kWh",
      potencia: "204 cv",
      torque: "250 Nm",
      aceleracao: "0–100 km/h em 8,6 s",
      velocidadeMax: "170 km/h",
      tracao: "Dianteira",
      recargaAC: "11 kW — 100% em ~6h30",
      recargaDC: "130 kW — 10% a 80% em ~29 min",
      lugares: 5,
      portaMalas: "490 L",
    },
    highlights: [
      "Tela curva BMW Curved Display",
      "Acabamento e dirigibilidade típicos da marca",
      "Espaço interno de SUV familiar",
    ],
    description:
      "O BMW iX1 entrega a experiência premium da marca em um SUV compacto totalmente elétrico. Boa autonomia, cabine refinada e o prazer de dirigir de um BMW.",
  },
  {
    id: "bmw-i4",
    brand: "BMW",
    model: "i4",
    tagline: "Gran Coupé elétrico para quem gosta de dirigir.",
    priceBRL: 449950,
    bodyType: "Sedã",
    segment: "Premium",
    color: "#1d4ed8",
    year: 2025,
    featured: false,
    specs: {
      autonomia: "483 km (WLTP)",
      bateria: "70,2 kWh",
      potencia: "286 cv",
      torque: "400 Nm",
      aceleracao: "0–100 km/h em 6,0 s",
      velocidadeMax: "190 km/h",
      tracao: "Traseira",
      recargaAC: "11 kW — 100% em ~7h",
      recargaDC: "180 kW — 10% a 80% em ~32 min",
      lugares: 5,
      portaMalas: "470 L",
    },
    highlights: [
      "Tração traseira e centro de gravidade baixo",
      "Porta-malas com tampa tipo liftback",
      "Recarga rápida de até 180 kW",
    ],
    description:
      "O BMW i4 une a silhueta de um cupê de quatro portas à dinâmica esportiva que fez a fama da marca. Um sedã elétrico para quem não abre mão do prazer ao volante.",
  },
  {
    id: "porsche-taycan",
    brand: "Porsche",
    model: "Taycan",
    tagline: "A alma de um Porsche, sem escapamento.",
    priceBRL: 720000,
    bodyType: "Sedã",
    segment: "Esportivo",
    color: "#a5b4fc",
    year: 2025,
    featured: true,
    specs: {
      autonomia: "590 km (WLTP)",
      bateria: "89 kWh",
      potencia: "435 cv",
      torque: "410 Nm",
      aceleracao: "0–100 km/h em 4,8 s",
      velocidadeMax: "230 km/h",
      tracao: "Traseira",
      recargaAC: "11 kW — 100% em ~9h",
      recargaDC: "320 kW — 10% a 80% em ~18 min",
      lugares: 4,
      portaMalas: "407 L",
    },
    highlights: [
      "Arquitetura de 800 V com recarga ultrarrápida",
      "Dinâmica de carro esportivo de verdade",
      "Acabamento e personalização Porsche",
    ],
    description:
      "O Porsche Taycan prova que um elétrico pode emocionar. Recarga entre as mais rápidas do mercado, comportamento de esportivo e o padrão de construção da marca alemã.",
  },
  {
    id: "mini-cooper-se",
    brand: "Mini",
    model: "Cooper SE",
    tagline: "Diversão de kart, energia de tomada.",
    priceBRL: 264990,
    bodyType: "Hatch",
    segment: "Premium",
    color: "#22d3ee",
    year: 2025,
    featured: false,
    specs: {
      autonomia: "402 km (WLTP)",
      bateria: "54,2 kWh",
      potencia: "218 cv",
      torque: "330 Nm",
      aceleracao: "0–100 km/h em 6,7 s",
      velocidadeMax: "170 km/h",
      tracao: "Dianteira",
      recargaAC: "11 kW — 100% em ~5h30",
      recargaDC: "95 kW — 10% a 80% em ~30 min",
      lugares: 4,
      portaMalas: "210 L",
    },
    highlights: [
      "Tela central redonda OLED",
      "Direção direta, o famoso go-kart feeling",
      "Visual inconfundível",
    ],
    description:
      "O Mini Cooper SE mantém tudo o que faz de um Mini um Mini — tamanho, estilo e agilidade — com um conjunto elétrico que deixa a condução ainda mais divertida.",
  },
  {
    id: "zeekr-x",
    brand: "Zeekr",
    model: "X",
    tagline: "SUV compacto premium com cara de futuro.",
    priceBRL: 272000,
    bodyType: "SUV",
    segment: "Premium",
    color: "#06b6d4",
    year: 2025,
    featured: false,
    specs: {
      autonomia: "440 km (WLTP)",
      bateria: "66 kWh",
      potencia: "272 cv",
      torque: "343 Nm",
      aceleracao: "0–100 km/h em 5,6 s",
      velocidadeMax: "180 km/h",
      tracao: "Traseira",
      recargaAC: "11 kW — 100% em ~7h",
      recargaDC: "150 kW — 10% a 80% em ~30 min",
      lugares: 5,
      portaMalas: "362 L",
    },
    highlights: [
      "Portas sem moldura e design ousado",
      "Cabine com materiais de alto padrão",
      "Desempenho forte para o porte",
    ],
    description:
      "O Zeekr X é a aposta da marca premium do grupo Geely para o segmento compacto. Visual marcante, interior caprichado e aceleração de esportivo.",
  },
  {
    id: "gac-aion-y",
    brand: "GAC",
    model: "Aion Y",
    tagline: "Espaço de sobra para a família.",
    priceBRL: 175990,
    bodyType: "SUV",
    segment: "Familiar",
    color: "#14b8a6",
    year: 2025,
    featured: false,
    specs: {
      autonomia: "318 km (Inmetro)",
      bateria: "63,2 kWh",
      potencia: "204 cv",
      torque: "225 Nm",
      aceleracao: "0–100 km/h em 8,5 s",
      velocidadeMax: "150 km/h",
      tracao: "Dianteira",
      recargaAC: "7 kW — 100% em ~10h",
      recargaDC: "80 kW — 30% a 80% em ~35 min",
      lugares: 5,
      portaMalas: "405 L",
    },
    highlights: [
      "Entre-eixos longo e bancos que viram cama",
      "Teto panorâmico",
      "Bom custo-benefício entre os SUVs elétricos",
    ],
    description:
      "O GAC Aion Y foi pensado de dentro para fora: muito espaço para pernas, cabine arejada e soluções práticas para o dia a dia da família.",
  },
  {
    id: "chevrolet-equinox-ev",
    brand: "Chevrolet",
    model: "Equinox EV",
    tagline: "O SUV elétrico da Chevrolet.",
    priceBRL: 419000,
    bodyType: "SUV",
    segment: "Familiar",
    color: "#2563eb",
    year: 2025,
    featured: false,
    specs: {
      autonomia: "443 km (Inmetro)",
      bateria: "85 kWh",
      potencia: "292 cv (AWD)",
      torque: "451 Nm",
      aceleracao: "0–100 km/h em 5,8 s",
      velocidadeMax: "180 km/h",
      tracao: "Integral (AWD)",
      recargaAC: "11 kW — 100% em ~9h",
      recargaDC: "150 kW — 10% a 80% em ~35 min",
      lugares: 5,
      portaMalas: "469 L",
    },
    highlights: [
      "Tração integral com dois motores",
      "Tela central de 17,7\"",
      "Rede de concessionárias em todo o país",
    ],
    description:
      "O Chevrolet Equinox EV traz autonomia para viagens, tração integral e muito espaço, com o suporte de uma das maiores redes de concessionárias do Brasil.",
  },
  {
    id: "mercedes-eqa",
    brand: "Mercedes-Benz",
    model: "EQA 250",
    tagline: "A estrela de três pontas em versão compacta.",
    priceBRL: 369900,
    bodyType: "SUV",
    segment: "Premium",
    color: "#94a3b8",
    year: 2025,
    featured: false,
    specs: {
      autonomia: "480 km (WLTP)",
      bateria: "66,5 kWh",
      potencia: "190 cv",
      torque: "385 Nm",
      aceleracao: "0–100 km/h em 8,6 s",
      velocidadeMax: "160 km/h",
      tracao: "Dianteira",
      recargaAC: "11 kW — 100% em ~7h15",
      recargaDC: "100 kW — 10% a 80% em ~32 min",
      lugares: 5,
      portaMalas: "340 L",
    },
    highlights: [
      "Sistema multimídia MBUX com comando de voz",
      "Conforto e isolamento acústico de Mercedes",
      "Assistentes de condução de série",
    ],
    description:
      "O Mercedes-Benz EQA 250 leva o conforto e a tecnologia da marca para um SUV compacto elétrico, ideal para quem roda na cidade e pega estrada no fim de semana.",
  },
  {
    id: "jac-e-js1",
    brand: "JAC",
    model: "E-JS1",
    tagline: "Pequeno, simples e 100% elétrico.",
    priceBRL: 126900,
    bodyType: "Hatch",
    segment: "Entrada",
    color: "#a78bfa",
    year: 2025,
    featured: false,
    specs: {
      autonomia: "181 km (Inmetro)",
      bateria: "30,2 kWh",
      potencia: "62 cv",
      torque: "150 Nm",
      aceleracao: "0–100 km/h em 14,0 s",
      velocidadeMax: "110 km/h",
      tracao: "Dianteira",
      recargaAC: "6,6 kW — 100% em ~5h",
      recargaDC: "40 kW — 20% a 80% em ~40 min",
      lugares: 4,
      portaMalas: "121 L",
    },
    highlights: [
      "Tamanho ideal para grandes centros",
      "Manutenção simples e barata",
      "Preço de entrada no mundo elétrico",
    ],
    description:
      "O JAC E-JS1 é um urbano compacto para quem roda pouco e quer gastar o mínimo por quilômetro. Direto ao ponto, sem complicação.",
  },
];

/**
 * Fotos reais dos modelos, baixadas do Wikimedia Commons (licenças livres).
 * `src` é a versão grande (1920px), `card` a menor (960px) para cards.
 * As licenças exigem citar autor e licença: o crédito aparece junto da foto
 * (photoCredit() em car-svg.js) e na página creditos.html.
 */
const CAR_PHOTOS = {
  "byd-dolphin": {
    src: "assets/carros/byd-dolphin.jpg",
    card: "assets/carros/byd-dolphin-960.jpg",
    author: "Alexander-93",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/deed.pt-br",
    page: "https://commons.wikimedia.org/wiki/File:BYD_Dolphin_IAA_2023_1X7A0634.jpg",
  },
  "byd-dolphin-mini": {
    src: "assets/carros/byd-dolphin-mini.jpg",
    card: "assets/carros/byd-dolphin-mini-960.jpg",
    author: "Alexander-93",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/deed.pt-br",
    page: "https://commons.wikimedia.org/wiki/File:BYD_Dolphin_Surf_IAA_2025_DSC_2256.jpg",
  },
  "byd-seal": {
    src: "assets/carros/byd-seal.jpg",
    card: "assets/carros/byd-seal-960.jpg",
    author: "Alexander-93",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/deed.pt-br",
    page: "https://commons.wikimedia.org/wiki/File:BYD_Seal_IAA_2023_1X7A0026.jpg",
  },
  "byd-yuan-plus": {
    src: "assets/carros/byd-yuan-plus.jpg",
    card: "assets/carros/byd-yuan-plus-960.jpg",
    author: "Alexander Migl",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/deed.pt-br",
    page: "https://commons.wikimedia.org/wiki/File:BYD_Atto_3_1X7A6495.jpg",
  },
  "byd-han": {
    src: "assets/carros/byd-han.jpg",
    card: "assets/carros/byd-han-960.jpg",
    author: "Alexander Migl",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/deed.pt-br",
    page: "https://commons.wikimedia.org/wiki/File:BYD_Han_EV_DSC_8759.jpg",
  },
  "byd-song-plus": {
    src: "assets/carros/byd-song-plus.jpg",
    card: "assets/carros/byd-song-plus-960.jpg",
    author: "Mateusmatsuda",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/deed.pt-br",
    page: "https://commons.wikimedia.org/wiki/File:BYD_SONG_PLUS_DM-I_FRONT.jpg",
  },
  "gwm-ora-03": {
    src: "assets/carros/gwm-ora-03.jpg",
    card: "assets/carros/gwm-ora-03-960.jpg",
    author: "Alexander-93",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/deed.pt-br",
    page: "https://commons.wikimedia.org/wiki/File:ORA_Funky_Cat_1X7A0814.jpg",
  },
  "byd-tan": {
    src: "assets/carros/byd-tan.jpg",
    card: "assets/carros/byd-tan-960.jpg",
    author: "Alexander-93",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/deed.pt-br",
    page: "https://commons.wikimedia.org/wiki/File:2024_BYD_Tang_GIMS_2024_1X7A2342.jpg",
  },
  "volvo-ex30": {
    src: "assets/carros/volvo-ex30.jpg",
    card: "assets/carros/volvo-ex30-960.jpg",
    author: "Alexander-93",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/deed.pt-br",
    page: "https://commons.wikimedia.org/wiki/File:Volvo_EX30_1X7A2476.jpg",
  },
  "renault-kwid-e-tech": {
    src: "assets/carros/renault-kwid-e-tech.jpg",
    card: "assets/carros/renault-kwid-e-tech-960.jpg",
    author: "Alexander Migl",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/deed.pt-br",
    page: "https://commons.wikimedia.org/wiki/File:Dacia_Spring_1X7A0350.jpg",
  },
  "fiat-500e": {
    src: "assets/carros/fiat-500e.jpg",
    card: "assets/carros/fiat-500e-960.jpg",
    author: "Alexander Migl",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/deed.pt-br",
    page: "https://commons.wikimedia.org/wiki/File:Fiat_500e_(2020)_Auto_Zuerich_2021_IMG_0604.jpg",
  },
  "peugeot-e-2008": {
    src: "assets/carros/peugeot-e-2008.jpg",
    card: "assets/carros/peugeot-e-2008-960.jpg",
    author: "Alexander Migl",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/deed.pt-br",
    page: "https://commons.wikimedia.org/wiki/File:Peugeot_e-2008_Automesse_Ludwigsburg_2022_1X7A5981.jpg",
  },
  "nissan-leaf": {
    src: "assets/carros/nissan-leaf.jpg",
    card: "assets/carros/nissan-leaf-960.jpg",
    author: "Alexander Migl",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/deed.pt-br",
    page: "https://commons.wikimedia.org/wiki/File:Nissan_Leaf_(ZE1)_DSC_7096.jpg",
  },
  "bmw-ix1": {
    src: "assets/carros/bmw-ix1.jpg",
    card: "assets/carros/bmw-ix1-960.jpg",
    author: "Alexander Migl",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/deed.pt-br",
    page: "https://commons.wikimedia.org/wiki/File:BMW_iX1_DSC_7507.jpg",
  },
  "bmw-i4": {
    src: "assets/carros/bmw-i4.jpg",
    card: "assets/carros/bmw-i4-960.jpg",
    author: "Alexander-93",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/deed.pt-br",
    page: "https://commons.wikimedia.org/wiki/File:BMW_i4_M50_1X7A7379.jpg",
  },
  "porsche-taycan": {
    src: "assets/carros/porsche-taycan.jpg",
    card: "assets/carros/porsche-taycan-960.jpg",
    author: "Alexander-93",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/deed.pt-br",
    page: "https://commons.wikimedia.org/wiki/File:2024_Porsche_Taycan_GTS_IAA_2025_DSC_1988.jpg",
  },
  "mini-cooper-se": {
    src: "assets/carros/mini-cooper-se.jpg",
    card: "assets/carros/mini-cooper-se-960.jpg",
    author: "Alexander-93",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/deed.pt-br",
    page: "https://commons.wikimedia.org/wiki/File:Mini_Hatch_(J01)_IMG_8959.jpg",
  },
  "zeekr-x": {
    src: "assets/carros/zeekr-x.jpg",
    card: "assets/carros/zeekr-x-960.jpg",
    author: "Matti Blume",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/deed.pt-br",
    page: "https://commons.wikimedia.org/wiki/File:Zeekr_X,_Almaty_(LRM_20240331_124050).jpg",
  },
  "gac-aion-y": {
    src: "assets/carros/gac-aion-y.jpg",
    card: "assets/carros/gac-aion-y-960.jpg",
    author: "Jengtingchen",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/deed.pt-br",
    page: "https://commons.wikimedia.org/wiki/File:Aion_Y_004.jpg",
  },
  "chevrolet-equinox-ev": {
    src: "assets/carros/chevrolet-equinox-ev.jpg",
    card: "assets/carros/chevrolet-equinox-ev-960.jpg",
    author: "JustAnotherCarDesigner",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.pt-br",
    page: "https://commons.wikimedia.org/wiki/File:Chevrolet_Equinox_EV_001.jpg",
  },
  "mercedes-eqa": {
    src: "assets/carros/mercedes-eqa.jpg",
    card: "assets/carros/mercedes-eqa-960.jpg",
    author: "Dinkun Chen",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/deed.pt-br",
    page: "https://commons.wikimedia.org/wiki/File:MERCEDES-BENZ_EQA_China.jpg",
  },
  "jac-e-js1": {
    src: "assets/carros/jac-e-js1.jpg",
    card: "assets/carros/jac-e-js1-960.jpg",
    author: "Matti Blume",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/deed.pt-br",
    page: "https://commons.wikimedia.org/wiki/File:JAC_e-JS1,_Auto_2024,_Zurich_(PANA0126).jpg",
  },
};
VEHICLES.forEach((v) => { if (CAR_PHOTOS[v.id]) v.photo = CAR_PHOTOS[v.id]; });

/** Marcas disponíveis (para filtros). */
const BRANDS = [...new Set(VEHICLES.map((v) => v.brand))].sort();

/** Tipos de carroceria (para filtros). */
const BODY_TYPES = [...new Set(VEHICLES.map((v) => v.bodyType))].sort();

/** Formata um número em Real brasileiro (R$). */
function formatBRL(value) {
  return value.toLocaleString("pt-BR", {
    style: "currency",
    currency: "BRL",
    maximumFractionDigits: 0,
  });
}

/** Primeiro número de um texto da ficha: "1.100 km" -> 1100, "44,9 kWh (Blade)" -> 44.9. */
function firstNumber(text) {
  const m = String(text).replace(/\./g, "").match(/\d+(,\d+)?/);
  return m ? parseFloat(m[0].replace(",", ".")) : 0;
}

/** Autonomia em km. */
function rangeKm(v) {
  return firstNumber(v.specs.autonomia);
}

/** Segundos de 0 a 100 km/h. */
function accelSeconds(v) {
  const m = v.specs.aceleracao.match(/([\d,]+) s/);
  return m ? parseFloat(m[1].replace(",", ".")) : 0;
}

/**
 * Consumo estimado em kWh a cada 100 km (bateria ÷ autonomia declarada).
 * Devolve null para híbridos, em que a autonomia "combinada" inclui gasolina.
 */
function consumptionKwh100(v) {
  const km = rangeKm(v);
  const kwh = firstNumber(v.specs.bateria);
  if (!km || !kwh || /combinada/i.test(v.specs.autonomia)) return null;
  return (kwh / km) * 100;
}

/** Busca um veículo pelo id. */
function getVehicleById(id) {
  return VEHICLES.find((v) => v.id === id) || null;
}
